name: Test Workflow
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Print Message
        run: echo "Implementing CI at ${{ github.repository_owner }} repo"

      - name: login to ghcr.io to push image
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: check pwd
        run: echo "pwd"

      - name: build image
        run: "docker build -t street-food-go .."
      - name: push image to ghcr.io packages
        run: "docker push ghcr.io/${{ github.repository_owner }}/street-food-go:${{ github.sha }}"